[inputs]
pkgs = {}

[floxEnv]
name = "ops-env"
postShellHook = '''
# Show versions with a bit of color
echo
LC_ALL=en_US.UTF-8 parallel --will-cite 'flox path-info $(readlink -f $(which {})) | cut -d- -f2- ' ::: curl docker unzip aws kubectl python3 helm |
   grep -P --colour=always '(?:^|(?<=[-]))[0-9.]*|$'
'''

[floxEnv.programs]
vscode = { extensions = ["ms-python.python", "ms-python.pylint"] }
kubernetes-helm = { version = "3.7" }

curl = {}
docker = {}
unzip = {}
awscli2 = {}
kubectl = {}

parallel = {}
gnugrep = {}
which = {}
coreutils = {}

[floxEnv.programs.python]
python = "python39"
requirements = '''
    pip
    allure-pytest==2.9.45
    kubernetes
    pytest
'''
